### ISSUE TITLE
getFood

### ISSUE THREAD

**Issue by camerondodd** [camerondodd/capstone1#3]
During user feedback, it was found that getFood is having some troubles.  It gives feed back, but not always for the correct city.  Also, citySubmit sometimes runs twice when the button is hit once and gives a blank entry.

While we are at it, sometimes getEvent doesn't find anything, which is fine, but how to I put a response saying there were no results that only shows up if there is nothing to render?

Also, I don't like the color scheme.  It looks kind of cheap.  Are there any tricks to make it look more professional?

**Comment by krokhale** [comment]
- First, Looks pretty neat and works great!

- Buttons clicking twice or events firing twice is a pretty common jQuery issue. Usually happens when you end up binding the element twice.

- This should help you: **https://stackoverflow.com/questions/14969960/jquery-click-events-firing-multiple-times**

- Also, feel free to google up jQuery on click event firing multiple times.

- When getEvent does its job, it calls back displayEventResults, After line 223, Check for the existence of data.events, if present, check for the number of events, if greater than 0, then do what you are already doing and display the results. If not

      $('.eventResults').html("<p>No results found!</p>");

That should do it.

- Though it's not covered in the course. But I would totally recommend Bootstrap. Read this: https://getbootstrap.com/docs/3.3/css/

- Once you read through, let's schedule a session to walk through how bootstrap works. We can have some quick pair programming on styling.

- I don't quite understand getFood troubles. Could you elaborate.

**Comment by camerondodd** [comment]
I fixed the citySubmit.  I wrote a script for the no results message for displayEventResults, but when I used it nothing on the page works, so I commented it out.  The problem with getFood, is that it is giving results for the wrong city more often than not.


Have a nice day,

Cameron Dodd, M.S.
Cameron.Dodd@mavs.uta.edu
________________________________

**Comment by camerondodd** [comment]
I fixed the getFood; it was an issue with the API, so I added another key to specify and now it's working perfectly.


Have a nice day,

Cameron Dodd, M.S.
Cameron.Dodd@mavs.uta.edu
________________________________

**Comment by krokhale** [comment]
Awesome, I just submitted a pull request for fixing displayEventResults. Let me know if everything is all set now.
